#include "stdio.h"
#include "stdlib.h"
#include <cassert>
#include "stdint.h"
#include <cmath>
#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <cstdint>
#include <functional>
#include <set>
#include <vector>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string.h>
#include "raylib.h"
#include "raymath.h"
